pipeline {
  agent any
    
  tools {nodejs "node"}
    
  stages {
        
    stage('Git') {
      steps {
        echo "Git  p2 step"
        // git 'https://github.com/hardik-stader/jenkins-test.git'
      }
    }
     
    stage('Build') {
      steps {
        echo "Build p2 step"
        // sh 'npm install'
        //  sh '<<Build Command>>'
      }
    }  
    
            
    stage('Test') {
      steps {

        echo "Test p2 step"
        // sh 'node test'
      }
    }
  }
}