pipeline { 
  
   agent any

   stages {
   
     stage('Install Dependencies') { 
        steps { 
            sh "npm install -g yarn"
            sh 'echo "p1 install"'
            sh 'cd apps/p1'
            sh 'yarn install'
            sh 'yarn build'
         }
      }
     
     stage('Test') { 
        steps { 
            sh 'echo "p1 testing application..."'
        }
      }

      stage("Deploy application") { 
         steps { 
            sh 'echo "p1 deploying application..."'
         }
      }
   }
}