pipeline { 
  
   agent any
   tools {nodejs "nodejs"}
   stages {
   
     stage('Install Dependencies') { 
        steps { 
            sh """npm install -g yarn
            echo "p1 install"
            ls
            cd apps/p1
            ls
            yarn install
            yarn build"""
         }
      }
     
     stage('Test') { 
        steps { 
            sh 'echo "p1 testing application..."'
            sh 'ls'
        }
      }

      stage("Deploy application") { 
         steps { 
            sh 'echo "p1 deploying application..."'
         }
      }
   }
}