pipeline { 
  
   agent any
   tools {nodejs "nodejs"}
   stages {
   
     stage('Install Dependencies') { 
        steps { 
            sh """npm install -g yarn
            echo "hedera install"
            ls
            cd apps/hedera
            ls
            yarn
            yarn build"""
         }
      }
     
     stage('Test') { 
        steps { 
            sh 'echo "hedera testing application..."'
            sh 'ls'
        }
      }

      stage("Deploy application") { 
         steps { 
            sh 'echo "hedera deploying application..."'
         }
      }
   }
}