pipeline { 
  
   agent any
   tools {nodejs "nodejs"}
   stages {
   
     stage('Install Dependencies') { 
        steps { 
            sh """npm install -g yarn
            echo "fantom install"
            ls
            cd apps/fantom
            ls
            yarn
            yarn build"""
         }
      }
     
     stage('Test') { 
        steps { 
            sh 'echo "fantom testing application..."'
            sh 'ls'
        }
      }

      stage("Deploy application") { 
         steps { 
            sh 'echo "fantom deploying application..."'
         }
      }
   }
}